
import PDFDocument from 'pdfkit';

/**
 * PraxisNow Negotiation Summary PDF Generator
 */

export interface NegotiationEvaluation {
    context: string;
    tactics_encountered: string[];
    strengths: string[];
    weak_phrasing: string[];
    strong_alternatives: string[];
    strategy_notes: string;
}

interface PDFMetadata {
    role: string;
    level: string;
    date: string;
    duration: string;
}

const COLORS = {
    primary: '#8b5cf6', // Violet
    secondary: '#94a3b8', // Slate 400
    dark: '#0f172a',    // Slate 900
    light: '#f8fafc',   // Slate 50
    accent: '#10b981',  // Emerald (Success)
    warning: '#f59e0b', // Amber
    error: '#ef4444',   // Red
    border: '#e2e8f0'   // Slate 200
};

const FONTS = {
    bold: 'Helvetica-Bold',
    regular: 'Helvetica',
};

export async function generateNegotiationPDF(
    evaluation: NegotiationEvaluation,
    metadata: PDFMetadata
): Promise<Buffer> {

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: 'A4',
            margin: 0,
            bufferPages: true
        });

        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // --- HELPERS ---

        const drawHeader = () => {
            const width = doc.page.width;

            // Violet top bar
            doc.rect(0, 0, width, 4).fill(COLORS.primary);

            doc.fontSize(10).fillColor(COLORS.secondary).font(FONTS.regular)
                .text('PRAXISNOW', 50, 40)
                .text('NEGOTIATION COACHING SUMMARY', 0, 40, { align: 'right', width: width - 50 });
        };

        const drawFooter = (pageNumber: number) => {
            const width = doc.page.width;
            const bottom = doc.page.height - 40;

            doc.moveTo(50, bottom - 15).lineTo(width - 50, bottom - 15).strokeColor(COLORS.border).stroke();

            doc.fontSize(8).fillColor(COLORS.secondary).font(FONTS.regular);
            doc.text(`Generated by PraxisNow • ${metadata.date}`, 50, bottom);
            doc.text(`${pageNumber}`, 0, bottom, { align: 'right', width: width - 50 });
        };

        // --- PAGE 1: OVERVIEW & TACTICS ---

        drawHeader();

        let y = 100;
        doc.fontSize(30).font(FONTS.bold).fillColor(COLORS.dark).text('Negotiation Summary', 50, y);
        y += 50;

        // Metadata
        doc.fontSize(12).font(FONTS.regular).fillColor(COLORS.secondary)
            .text(`${metadata.role} • ${metadata.level} • ${metadata.duration}`, 50, y);

        y += 40;

        // Context Section
        doc.rect(50, y, 500, 80).fillColor('#f5f3ff').fill(); // Light violet bg
        doc.fillColor(COLORS.dark).font(FONTS.bold).fontSize(12).text('CONTEXT', 70, y + 20);
        doc.fillColor(COLORS.dark).font(FONTS.regular).fontSize(10)
            .text(evaluation.context || "No context provided.", 70, y + 40, { width: 460 });

        y += 110;

        // Tactics Encountered
        doc.fontSize(14).font(FONTS.bold).fillColor(COLORS.dark).text('Employer Tactics Encountered', 50, y);
        y += 30;

        evaluation.tactics_encountered.forEach((tactic) => {
            doc.rect(50, y, 4, 30).fillColor(COLORS.warning).fill();
            doc.rect(54, y, 496, 30).fillColor(COLORS.light).fill();
            doc.fillColor(COLORS.dark).font(FONTS.regular).fontSize(11).text(tactic, 70, y + 10);
            y += 40;
        });

        // Strengths
        y += 20;
        doc.fontSize(14).font(FONTS.bold).fillColor(COLORS.dark).text('Your Leverage & Strengths', 50, y);
        y += 30;

        evaluation.strengths.forEach((str) => {
            doc.circle(55, y + 6, 3).fillColor(COLORS.accent).fill();
            doc.fillColor(COLORS.dark).font(FONTS.regular).fontSize(11).text(str, 70, y);
            y += 25;
        });

        drawFooter(1);

        // --- PAGE 2: COACHING ANALYSIS ---
        doc.addPage();
        drawHeader();
        y = 80;

        doc.fontSize(16).font(FONTS.bold).fillColor(COLORS.dark).text('Phrase Optimization', 50, y);
        y += 40;

        // Weak vs Strong Table-like structure
        doc.fontSize(12).font(FONTS.bold).fillColor(COLORS.error).text('AVOID (Weak Phrasing)', 50, y, { width: 220 });
        doc.fillColor(COLORS.accent).text('USE INSTEAD (Stronger)', 290, y, { width: 220 });
        y += 25;
        doc.moveTo(50, y).lineTo(545, y).strokeColor(COLORS.border).stroke();
        y += 20;

        // We assume weak_phrasing and strong_alternatives are parallel arrays of same length
        const maxItems = Math.max(evaluation.weak_phrasing.length, evaluation.strong_alternatives.length);

        for (let i = 0; i < maxItems; i++) {
            const weak = evaluation.weak_phrasing[i] || "";
            const strong = evaluation.strong_alternatives[i] || "";

            const startY = y;

            // Weak col
            doc.font(FONTS.regular).fontSize(10).fillColor(COLORS.dark).text(weak, 50, y, { width: 220 });
            const h1 = doc.heightOfString(weak, { width: 220 });

            // Strong col
            doc.text(strong, 290, y, { width: 220 });
            const h2 = doc.heightOfString(strong, { width: 220 });

            y += Math.max(h1, h2) + 20;

            // Separator
            if (i < maxItems - 1) {
                doc.moveTo(50, y - 10).lineTo(545, y - 10).strokeColor('#f1f5f9').stroke();
            }
        }

        y += 30;

        // Strategy Notes
        doc.fontSize(16).font(FONTS.bold).fillColor(COLORS.dark).text('Coach\'s Strategy Notes', 50, y);
        y += 30;

        doc.rect(50, y, 500, 150).fillColor('#f0f9ff').fill(); // Light blue
        doc.rect(50, y, 4, 150).fillColor('#0ea5e9').fill(); // Blue accent

        doc.fillColor(COLORS.dark).font(FONTS.regular).fontSize(11)
            .text(evaluation.strategy_notes, 70, y + 20, { width: 460, align: 'justify' });

        drawFooter(2);
        doc.end();
    });
}
